spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/userdbdev
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 'P@ssw0rd'
  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        '[format_sql]': true
  sql:
    init:
      platform: mysql
      data-locations: classpath:data-mysql.sql
      mode: always
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: false
      retry:
        maxAttempts: 20

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  servlet:
    context-path: /api/user-service

api-config:
  jwt-config:
    jwt-disabled: true
    jwt-secret: secret
    jwt-validity: 20